apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydotnetapp
  namespace: my-app-namespace
  labels:
    app: mydotnetapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydotnetapp
  template:
    metadata:
      labels:
        app: mydotnetapp
    spec:
      containers:
      - name: mydotnetapp
        image: myacrregistry123456789.azurecr.io/mydotnetapp:latest
        ports:
        - containerPort: 80
