apiVersion: v1
kind: Service
metadata:
  name: mydotnetapp-svc
  namespace: my-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: mydotnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
